export const siteGraph = {
  origin: "https://www.reformcollective.com",
  pages: [
    {
      id: "home",
      path: "/",
      title: "Home / Agency",
      sections: [
        "nav",
        "hero-intro",
        "featured-work",
        "manifesto",
        "nova-cta",
        "footer",
      ],
    },
    {
      id: "work",
      path: "/work",
      title: "Work Index",
      sections: ["nav", "work-intro", "work-grid", "footer"],
    },
    {
      id: "case-study",
      path: "/work/[slug]",
      title: "Case Study",
      sections: [
        "nav",
        "case-hero",
        "case-body",
        "case-media",
        "case-next",
        "footer",
      ],
    },
    {
      id: "about",
      path: "/about",
      title: "About / Capabilities",
      sections: [
        "nav",
        "about-hero",
        "marquee",
        "capabilities",
        "people",
        "testimonials",
        "footer",
      ],
    },
    {
      id: "nova",
      path: "/nova",
      title: "Nova Accelerator",
      sections: ["nav-minimal", "nova-hero", "nova-body", "faq", "apply"],
    },
    {
      id: "contact",
      path: "/contact",
      title: "Contact / Book a Call",
      sections: ["nav", "contact-hero", "contact-form", "footer"],
    },
  ],
  shared: {
    nav: "{%part:nav-primary%}",
    menu: "{%part:nav-menu-overlay%}",
    footer: "{%part:section-footer%}",
  },
  motion: [
    "{%motion:mask-reveal%}",
    "{%motion:featured-scroll%}",
    "{%motion:marquee-details%}",
    "{%motion:capability-stagger%}",
    "{%motion:testimonial-swap%}",
    "{%motion:nova-mega-type%}",
    "{%motion:lenis-scroll%}",
  ],
  crawlDepth: {
    primary: ["/", "/work", "/about", "/nova", "/contact"],
    caseStudies: [
      "/work/circle",
      "/work/enzo",
      "/work/runway",
      "/work/campfire",
      "/work/nervana",
      "/work/delphi",
      "/work/aerodome",
      "/work/micro",
      "/strider",
      "/arlo",
      "/journey",
      "/newform",
      "/titan-intake",
      "/thoughtly",
      "/boost-insurance",
      "/impilo",
      "/reform-co-response",
    ],
    utility: ["/apply-for-nova", "/home"],
  },
} as const;
